[package]
name = "bugtools-dns"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
bugtools-core = { path = "../bugtools-core" }
tokio = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
hickory-resolver = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
