[package]
name = "bugtools-xss"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
bugtools-core = { path = "../bugtools-core" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
regex = { workspace = true }
uuid = { workspace = true }
scraper = { workspace = true }
