// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.25.1
// source: events.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	TargetId      string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestJob) Reset() {
	*x = RequestJob{}
	mi := &file_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestJob) ProtoMessage() {}

func (x *RequestJob) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestJob.ProtoReflect.Descriptor instead.
func (*RequestJob) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{0}
}

func (x *RequestJob) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *RequestJob) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *RequestJob) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RequestJob) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *RequestJob) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *RequestJob) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type RequestObservation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	JobId           string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ObservationId   string                 `protobuf:"bytes,2,opt,name=observation_id,json=observationId,proto3" json:"observation_id,omitempty"`
	Status          uint32                 `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Headers         map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body            []byte                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	ElapsedMs       uint64                 `protobuf:"varint,6,opt,name=elapsed_ms,json=elapsedMs,proto3" json:"elapsed_ms,omitempty"`
	TimestampUnixMs uint64                 `protobuf:"varint,7,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RequestObservation) Reset() {
	*x = RequestObservation{}
	mi := &file_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestObservation) ProtoMessage() {}

func (x *RequestObservation) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestObservation.ProtoReflect.Descriptor instead.
func (*RequestObservation) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{1}
}

func (x *RequestObservation) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *RequestObservation) GetObservationId() string {
	if x != nil {
		return x.ObservationId
	}
	return ""
}

func (x *RequestObservation) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RequestObservation) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *RequestObservation) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *RequestObservation) GetElapsedMs() uint64 {
	if x != nil {
		return x.ElapsedMs
	}
	return 0
}

func (x *RequestObservation) GetTimestampUnixMs() uint64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

// Common Event Envelope for the Event Bus
type EventEnvelope struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EventId         string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	JobId           string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	WorkerId        string                 `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Engine          string                 `protobuf:"bytes,4,opt,name=engine,proto3" json:"engine,omitempty"`
	EngineVersion   string                 `protobuf:"bytes,5,opt,name=engine_version,json=engineVersion,proto3" json:"engine_version,omitempty"`
	TimestampUnixMs uint64                 `protobuf:"varint,6,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	EventType       string                 `protobuf:"bytes,7,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // e.g., "HTTP_OBSERVATION", "DNS_OBSERVATION"
	Payload         []byte                 `protobuf:"bytes,8,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	mi := &file_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{2}
}

func (x *EventEnvelope) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventEnvelope) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *EventEnvelope) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *EventEnvelope) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *EventEnvelope) GetEngineVersion() string {
	if x != nil {
		return x.EngineVersion
	}
	return ""
}

func (x *EventEnvelope) GetTimestampUnixMs() uint64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

func (x *EventEnvelope) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_events_proto protoreflect.FileDescriptor

const file_events_proto_rawDesc = "" +
	"\n" +
	"\fevents.proto\x12\vbugtools.v1\"\xfa\x01\n" +
	"\n" +
	"RequestJob\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12>\n" +
	"\aheaders\x18\x05 \x03(\v2$.bugtools.v1.RequestJob.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x06 \x01(\fR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcd\x02\n" +
	"\x12RequestObservation\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12%\n" +
	"\x0eobservation_id\x18\x02 \x01(\tR\robservationId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\rR\x06status\x12F\n" +
	"\aheaders\x18\x04 \x03(\v2,.bugtools.v1.RequestObservation.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x05 \x01(\fR\x04body\x12\x1d\n" +
	"\n" +
	"elapsed_ms\x18\x06 \x01(\x04R\telapsedMs\x12*\n" +
	"\x11timestamp_unix_ms\x18\a \x01(\x04R\x0ftimestampUnixMs\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x82\x02\n" +
	"\rEventEnvelope\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\x12\x16\n" +
	"\x06engine\x18\x04 \x01(\tR\x06engine\x12%\n" +
	"\x0eengine_version\x18\x05 \x01(\tR\rengineVersion\x12*\n" +
	"\x11timestamp_unix_ms\x18\x06 \x01(\x04R\x0ftimestampUnixMs\x12\x1d\n" +
	"\n" +
	"event_type\x18\a \x01(\tR\teventType\x12\x18\n" +
	"\apayload\x18\b \x01(\fR\apayload2]\n" +
	"\vCoordinator\x12N\n" +
	"\x0eExecuteHttpJob\x12\x17.bugtools.v1.RequestJob\x1a\x1f.bugtools.v1.RequestObservation\"\x000\x01B!Z\x1fbugtools/http-go/internal/protob\x06proto3"

var (
	file_events_proto_rawDescOnce sync.Once
	file_events_proto_rawDescData []byte
)

func file_events_proto_rawDescGZIP() []byte {
	file_events_proto_rawDescOnce.Do(func() {
		file_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)))
	})
	return file_events_proto_rawDescData
}

var file_events_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_events_proto_goTypes = []any{
	(*RequestJob)(nil),         // 0: bugtools.v1.RequestJob
	(*RequestObservation)(nil), // 1: bugtools.v1.RequestObservation
	(*EventEnvelope)(nil),      // 2: bugtools.v1.EventEnvelope
	nil,                        // 3: bugtools.v1.RequestJob.HeadersEntry
	nil,                        // 4: bugtools.v1.RequestObservation.HeadersEntry
}
var file_events_proto_depIdxs = []int32{
	3, // 0: bugtools.v1.RequestJob.headers:type_name -> bugtools.v1.RequestJob.HeadersEntry
	4, // 1: bugtools.v1.RequestObservation.headers:type_name -> bugtools.v1.RequestObservation.HeadersEntry
	0, // 2: bugtools.v1.Coordinator.ExecuteHttpJob:input_type -> bugtools.v1.RequestJob
	1, // 3: bugtools.v1.Coordinator.ExecuteHttpJob:output_type -> bugtools.v1.RequestObservation
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_events_proto_init() }
func file_events_proto_init() {
	if File_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_events_proto_goTypes,
		DependencyIndexes: file_events_proto_depIdxs,
		MessageInfos:      file_events_proto_msgTypes,
	}.Build()
	File_events_proto = out.File
	file_events_proto_goTypes = nil
	file_events_proto_depIdxs = nil
}
