[package]
name = "bugtools-nosql"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
bugtools-core = { path = "../bugtools-core" }
bugtools-scope = { path = "../bugtools-scope" }
bugtools-http = { path = "../bugtools-http" }
tokio = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
url = { workspace = true }
