pub mod error_based;
pub mod time_based;
pub mod syntax_features;
pub mod clause_variants;
pub mod boolean_based;
pub mod union_based;

use crate::types::ProbeType;
use crate::clause_map::SqlClause;
use crate::detection::DbmsFamily;

/// A payload definition generated by an expert module.
#[derive(Debug, Clone)]
pub struct GeneratedPayload {
    pub name: String,
    pub probe_type: ProbeType,
    pub payload_str: String,
    pub expected_dbms: Option<DbmsFamily>,
    pub clause: Option<SqlClause>,
}
